version: '3.7'

services:
  db:
    image: postgres:12
    container_name: db_for_${PROJECT_NAME}
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  dev-deps:
    image: busybox:1.34.1
    depends_on:
      - db

volumes:
  data:
    driver: local
